# Site settings
title: Mason's Homepage
tag_text: Mason Malone
description: Home page for Mason Malone, a software developer in Seattle, WA

# Build settings
markdown: kramdown
exclude: ["README.md", "LICENSE"]
sass:
  style: compressed
